package com.demo.models;
// Generated Jan 28, 2022 6:36:54 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;

import org.hibernate.annotations.Parent;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.Range;



/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "sem_project")
public class Account implements java.io.Serializable {
    
	@Length(min = 7,max=20)
	@NotEmpty 
	private String username;
	// Tan123456
	@NotEmpty 
	private String password;
	
	@NotEmpty 
	private String fullname;
	@NotEmpty 
	@Pattern(regexp="(^$|[0-9]{10})")
	private String phone;
	
	private boolean status;
	private Set<Contact> contacts = new HashSet<Contact>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Restaurant> restaurants = new HashSet<Restaurant>(0);

	public Account() {
	}

	public Account(String username, String password, String fullname, String phone, boolean status) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.phone = phone;
		this.status = status;
	}

	public Account(String username, String password, String fullname, String phone, boolean status,
			Set<Contact> contacts, Set<Order> orders, Set<Role> roles, Set<Restaurant> restaurants) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.phone = phone;
		this.status = status;
		this.contacts = contacts;
		this.orders = orders;
		this.roles = roles;
		this.restaurants = restaurants;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullname", nullable = false, length = 250)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}
@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "account_role", catalog = "sem_project", joinColumns = {
			@JoinColumn(name = "username", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "acccount_res", catalog = "sem_project", joinColumns = {
			@JoinColumn(name = "username", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "res_id", nullable = false, updatable = false) })
	public Set<Restaurant> getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set<Restaurant> restaurants) {
		this.restaurants = restaurants;
	}

}