package com.demo.models;
// Generated Jan 28, 2022 6:36:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name = "discount", catalog = "sem_project")
public class Discount implements java.io.Serializable {

	private Integer id;
	private Restaurant restaurant;
	private String name;
	private double money;
	private double fromMoney;
	private String description;
	private String photo;
	private boolean status;

	public Discount() {
	}

	public Discount(Restaurant restaurant, String name, double money, double fromMoney, String description,
			String photo, boolean status) {
		this.restaurant = restaurant;
		this.name = name;
		this.money = money;
		this.fromMoney = fromMoney;
		this.description = description;
		this.photo = photo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "money", nullable = false, precision = 22, scale = 0)
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	@Column(name = "from_money", nullable = false, precision = 22, scale = 0)
	public double getFromMoney() {
		return this.fromMoney;
	}

	public void setFromMoney(double fromMoney) {
		this.fromMoney = fromMoney;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "photo", nullable = false, length = 25)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
