package com.demo.models;
// Generated Jan 28, 2022 6:36:54 PM by Hibernate Tools 5.1.7.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "sem_project")
public class Menu implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Restaurant restaurant;
	private String name;
	private double price;
	private String description;
	private boolean status;
	private List<Photo> photos = new ArrayList<Photo>();
	private Set<OrderMenu> orderMenus = new HashSet<OrderMenu>(0);

	public Menu() {
	}

	public Menu(Category category, Restaurant restaurant, String name, double price, String description,
			boolean status) {
		this.category = category;
		this.restaurant = restaurant;
		this.name = name;
		this.price = price;
		this.description = description;
		this.status = status;
	}

	public Menu(Category category, Restaurant restaurant, String name, double price, String description, boolean status,
			List<Photo> photos, Set<OrderMenu> orderMenus) {
		this.category = category;
		this.restaurant = restaurant;
		this.name = name;
		this.price = price;
		this.description = description;
		this.status = status;
		this.photos = photos;
		this.orderMenus = orderMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public List<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(List<Photo> photos) {
		this.photos = photos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<OrderMenu> getOrderMenus() {
		return this.orderMenus;
	}

	public void setOrderMenus(Set<OrderMenu> orderMenus) {
		this.orderMenus = orderMenus;
	}

}
