package com.demo.models;
// Generated Jan 28, 2022 6:36:54 PM by Hibernate Tools 5.1.7.Final

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "sem_project")
public class Order implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Restaurant restaurant;
	private Date date;
	private double total;
	private Set<OrderTable> orderTables = new HashSet<OrderTable>(0);
	private Set<OrderMenu> orderMenus = new HashSet<OrderMenu>(0);

	public Order() {
	}

	public Order(Account account, Restaurant restaurant, Date date, double total) {
		this.account = account;
		this.restaurant = restaurant;
		this.date = date;
		this.total = total;
	}

	public Order(Account account, Restaurant restaurant, Date date, double total, Set<OrderTable> orderTables,
			Set<OrderMenu> orderMenus) {
		this.account = account;
		this.restaurant = restaurant;
		this.date = date;
		this.total = total;
		this.orderTables = orderTables;
		this.orderMenus = orderMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_id", nullable = false)
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date2) {
		this.date = date2;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderTable> getOrderTables() {
		return this.orderTables;
	}

	public void setOrderTables(Set<OrderTable> orderTables) {
		this.orderTables = orderTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderMenu> getOrderMenus() {
		return this.orderMenus;
	}

	public void setOrderMenus(Set<OrderMenu> orderMenus) {
		this.orderMenus = orderMenus;
	}

}
