package com.demo.models;
// Generated Jan 28, 2022 6:36:54 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restaurant generated by hbm2java
 */
@Entity
@Table(name = "restaurant", catalog = "sem_project")
public class Restaurant implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String address;
	private String email;
	private String phone;
	private String photo;
	private String description;
	private boolean status;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<Tables> tableses = new HashSet<Tables>(0);
	private Set<Discount> discounts = new HashSet<Discount>(0);
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Category> categories = new HashSet<Category>(0);

	public Restaurant() {
	}

	public Restaurant(String fullname, String address, String email, String phone, String photo, String description,
			boolean status) {
		this.fullname = fullname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.photo = photo;
		this.description = description;
		this.status = status;
	}

	public Restaurant(String fullname, String address, String email, String phone, String photo, String description,
			boolean status, Set<Order> orders, Set<Tables> tableses, Set<Discount> discounts, Set<Account> accounts,
			Set<Menu> menus, Set<Category> categories) {
		this.fullname = fullname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.photo = photo;
		this.description = description;
		this.status = status;
		this.orders = orders;
		this.tableses = tableses;
		this.discounts = discounts;
		this.accounts = accounts;
		this.menus = menus;
		this.categories = categories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = false, length = 250)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "email", nullable = false, length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "photo", nullable = false, length = 50)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Tables> getTableses() {
		return this.tableses;
	}

	public void setTableses(Set<Tables> tableses) {
		this.tableses = tableses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Discount> getDiscounts() {
		return this.discounts;
	}

	public void setDiscounts(Set<Discount> discounts) {
		this.discounts = discounts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "acccount_res", catalog = "sem_project", joinColumns = {
			@JoinColumn(name = "res_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "username", nullable = false, updatable = false) })
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurant")
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

}
